baseURL = "https://mdsz.ca/"
languageCode = "en-us"
title = "Matthew do Santos-Zounon"
theme = "terminal"
publishDir = "docs"

[pagination]
  pagerSize = 5
enableRobotsTXT = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false

[params]
  contentTypeName = "projects"
  showMenuItems = 0
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  readMore = "Open"
  readOtherPosts = "More projects"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Matthew do Santos-Zounon"
    subtitle = "Software engineer + student"
    menuMore = "More"
    readMore = "Read"
    readOtherPosts = "More projects"

    [languages.en.params.logo]
      logoText = "Matt dSZ"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/do_santos_zounon_resume.pdf"
        weight = 10
        [languages.en.menu.main.params]
          align = "right"
          newtab = true
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/Zounon"
        weight = 11
        [languages.en.menu.main.params]
          align = "right"
          newtab = true
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/mdsz/"
        weight = 12
        [languages.en.menu.main.params]
          align = "right"
          newtab = true
      [[languages.en.menu.main]]
        identifier = "email"
        name = "Email"
        url = "mailto:matthewsantos314@gmail.com"
        weight = 13
        [languages.en.menu.main.params]
          align = "right"
